### ISSUE TITLE
UnicodeDecodeError in winnower

### ISSUE THREAD

**Issue by technoskald** [mlsecproject/combine#104]
Traceback (most recent call last):
  File "winnower.py", line 184, in <module>
    winnow('crop.json', 'crop.json', 'enriched.json')
  File "winnower.py", line 180, in winnow
    json.dump(enriched, f, indent=2)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 313, in _iterencode_list
    yield buf + _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 27: unexpected end of data

![kirk-unicode](https://cloud.githubusercontent.com/assets/1624387/5559004/82b051fc-8d01-11e4-90d8-cd9ca1b6679a.jpg)

**Comment by technoskald** [comment]
oops, I thought that one was from another project, I even used the same reaction graphic!

**Comment by alexcpsec** [comment]
The projects may change, but the Unicode rage remains the same.

**Comment by technoskald** [comment]
![rat-in-a-cage](https://cloud.githubusercontent.com/assets/1624387/5652993/c77be822-967b-11e4-8720-d4e84d6d7900.jpg)

**Comment by alexcpsec** [comment]
Fixed by #103
