### ISSUE TITLE
PROTOCOL_SSLv3 is not defined

### ISSUE THREAD

**Issue by aleixsb** [mlsecproject/combine#160]
Hi all,

I've followed all steps in the descriptions but I'm getting the following error... Anyone knows why?

Traceback (most recent call last):
  File "reaper.py", line 2, in <module>
    import grequests
  File "/home/xx/Desktop/combine/combine/venv/src/grequests-origin/grequests.py", line 21, in <module>
    curious_george.patch_all(thread=False, select=False)
  File "/home/xx/Desktop/combine/combine/venv/local/lib/python2.7/site-packages/gevent/monkey.py", line 185, in patch_all
    patch_socket(dns=dns, aggressive=aggressive)
  File "/home/xx/Desktop/combine/combine/venv/local/lib/python2.7/site-packages/gevent/monkey.py", line 124, in patch_socket
    from gevent import socket
  File "/home/xx/Desktop/combine/combine/venv/local/lib/python2.7/site-packages/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/home/xx/Desktop/combine/combine/venv/local/lib/python2.7/site-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined

**Comment by alexcpsec** [comment]
Yeah, it seems our `grequests` patch is showing it's age. :/

I can try taking a look at it this for you, but what I would try to do at first is update the `requirements.txt` file to be able to include the latest versions of `gevent`, `requests` and  `grequests`. They were broken for the longest time, and had forced us to freeze on those weird versions.

If you are comfortable enough with Python dependencies and have some time, could you please let me know if you can fix it? Otherwise, I will get to it as soon as I can (might be a while, though :( )

**Comment by Darkan** [comment]
Hey guys, as python dropped SSL due to POODLE and etc. we need to update gevent accordingly.
As gevent uses TLS in recent versions, this error will disappear after the upgrade.

To fix this error open requirements.txt and replace gevent==1.0.1 with gevent>=1.0.1.

**Comment by alexcpsec** [comment]
@aleixsb I have merged this into master. Could you please check that this is resolved?

**Comment by aleixsb** [comment]
Now it's working perfect! Thank you for your time!

**Comment by alexcpsec** [comment]
Thanks to @Darkan  :) Closing this now.
